import { Container } from '@/components/atoms/Container/Container'
import { Header } from '@/components/organisms/Header/Header'
import '@/styles/globals.css'
import type { Metadata } from 'next'
import { Open_Sans } from 'next/font/google'

const openSans = Open_Sans({
  subsets: ['latin'],
  weight: ['400', '500'],
  display: 'swap',
  variable: '--font-open-sans',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html
      lang="en"
      className={`${openSans.variable}`}
    >
      <body>
        <Header />
        <Container>{children}</Container>
      </body>
    </html>
  )
}
